apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: watika-gardenia-image-updater
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "watika-gardenia-*"

      commonUpdateSettings:
        updateStrategy: "newest-build"
        allowTags: "regexp:^sha-[a-f0-9]{7,40}$"

      images:
        - alias: frontend
          imageName: ghcr.io/mkkarn/watika-gardenia-frontend

        - alias: menu
          imageName: ghcr.io/mkkarn/watika-gardenia-menu

        - alias: cart
          imageName: ghcr.io/mkkarn/watika-gardenia-cart

        - alias: orders
          imageName: ghcr.io/mkkarn/watika-gardenia-orders

        - alias: payment
          imageName: ghcr.io/mkkarn/watika-gardenia-payment

        - alias: recommendation
          imageName: ghcr.io/mkkarn/watika-gardenia-recommendation

        - alias: auth
          imageName: ghcr.io/mkkarn/watika-gardenia-auth

        - alias: loadgenerator
          imageName: ghcr.io/mkkarn/watika-gardenia-loadgenerator

        - alias: orders-db
          imageName: ghcr.io/mkkarn/watika-gardenia-orders-db

