# lbconfig.yaml
apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: app-gw-lbconfig
  namespace: default
spec:
  scheme: internet-facing
  listenerConfigurations:
    - protocolPort: HTTPS:443
      defaultCertificate:arn:aws:acm:ap-south-1:439440559037:certificate/e89184f2-db2c-43bd-a44b-a2c2a3708bc9
