apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: restaurant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - name: loadgenerator
        image: ghcr.io/mkkarn/watika-gardenia-loadgenerator:latest
        args: ["-c", "while true; do curl -s http://frontend; sleep 1; done"]

