apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service
  namespace: restaurant-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
      - name: menu-service
        image: ghcr.io/mkkarn/watika-gardenia-menu-service:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
  namespace: restaurant-app
spec:
  type: ClusterIP
  selector:
    app: menu-service
  ports:
  - port: 8081
    targetPort: 8081

